spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
        open-in-view: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-large
    vectorstore:
      pinecone:
        api-key: ${PINECONE_API_KEY}
        index-name: ${PINECONE_INDEX}
        namespace: ${PINECONE_NAMESPACE}
        content-field-name: document_content

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.zaxxer.hikari: debug

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS}

kakao:
  client_id: ${REST_API_KEY}
  redirect_uri: ${KAKAO_REDIRECT_URI}

tour-api:
  secret-key: ${TOUR_API_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info

cloud:
  aws:
    s3:
      bucket: hiddencountry
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

